export const VERSION = '0.1.1';
export * from './types.js';
export * from './errors.js';
export { escape } from './escaping.js';
export { render } from './render.js';
export type { TemplateRef, RenderOptions, RenderResult } from './render.js';
export { SlackClient } from './slack-client.js';
export { loadConfig } from './config.js';
export { resolveTokenFrom } from './config.js';
export type { SlackConfig, TokenType, TokenEnv } from './config.js';
export { Resolver } from './resolver.js';
export { findOrCreate } from './idempotency.js';
export type { FindOrCreateArgs, FindOrCreateResult } from './idempotency.js';
export { normalize, parityDiff } from './parity-normalize.js';
export { discoverParityCases } from './parity-cases.js';
export type { ParityCase } from './parity-cases.js';
export { validateStructural } from './structural.js';
export { validateLimits } from './limits.js';
export { deriveFallback } from './fallback.js';
